/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Medidas;


import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.group.sistema.Sistema;
import com.github.britooo.looca.api.util.Conversor;
import java.awt.Color;
import java.util.List;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author rmsouza
 */
public class TelaInfMaquina extends javax.swing.JFrame {
//CONEXAO BANCO
       Medidas.ConexaoTechHealth connection = new Medidas.ConexaoTechHealth();
       JdbcTemplate banco = connection.getConexao(); 
        
       //CRIANDO O LOOCA + INSTANCIANDO OUTRAS CLASSES DAS MEDIDAS
       Looca looca = new Looca();
       Computador comp = new Computador();
       Processador processador = new Processador();
       Sistema sistema = new Sistema();
       Memoria memoria = new Memoria();
       Conversor conversor = new Conversor();
       
       //CRIANDO VARIAVES DAS MEDIDAS
        
        String nome_Processador = processador.getNome();
        Integer numero_CPU_fisica = processador.getNumeroCpusFisicas();
        //Long capacidade_Total_Memoria = Conversor.formatarBytes(memoria.getTotal());   -------- PS: essa foi direto no insert
        String sistema_Operacional = sistema.getSistemaOperacional();
        String fabricante = sistema.getFabricante();
        
    /**
     * Creates new form TelaInfMaquina
     */
    public TelaInfMaquina() {
        initComponents();
        
        //MAQUINA 1
        Computador comp1 = new Computador();
        List<Computador> listaMaquina01 = banco.query("select idMaquina, Hospital.nome_Hospital, ala_Hospitalar, sistema_Operacional, fabricante, nome_Processador, "
                + "frequencia_Processador, capacidade_Total_Memoria, tamanho_Disco, numero_CPU_fisica from maquina\n" +
        "right join hospital on maquina.fkHospital = hospital.idHospital where idMaquina = 1;", new BeanPropertyRowMapper(Computador.class));
        
        lblIdMaq01.setText(listaMaquina01.get(0).getIdMaquina().toString());
        lblAlaMaq01.setText(listaMaquina01.get(0).getAla_Hospitalar());
        lblSist_OperMaq01.setText(listaMaquina01.get(0).getSistema_Operacional());
        lblFabricanMaq01.setText(listaMaquina01.get(0).getFabricante());
        lblNomProcessMaq01.setText(listaMaquina01.get(0).getNome_Processador());
        lblFreqProcessMaq01.setText(listaMaquina01.get(0).getFrequencia_Processador());
        lblTotMemoMaq01.setText(listaMaquina01.get(0).getCapacidade_Total_Memoria());
        lblTotDiscoMaq01.setText(listaMaquina01.get(0).getTamanho_Disco());
        lblNumCpuFisMaq01.setText(listaMaquina01.get(0).getNumero_CPU_fisica().toString());
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblHospital01 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAlaMaq01 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSist_OperMaq01 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFabricanMaq01 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNomProcessMaq01 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JLabel();
        lblTotMemMaq2 = new javax.swing.JLabel();
        lblTotMemoMaq01 = new javax.swing.JLabel();
        lblTotDiscoMaq01 = new javax.swing.JLabel();
        lblTotMemMaq3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblIdMaq01 = new javax.swing.JLabel();
        lblNumCpuFisMaq01 = new javax.swing.JLabel();
        btnVerMedidas = new javax.swing.JButton();
        lblFreqProcessMaq01 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Informações da Máquina");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ala Hospitalar:");

        lblAlaMaq01.setText("---------");

        lblSist_OperMaq01.setText("--------");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sistema Operacional:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Fabricante:");

        lblFabricanMaq01.setText("--------");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Processador:");

        lblNomProcessMaq01.setText("--------");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Frequencia do Processador:");

        txtCapacidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCapacidade.setText("Capacidade Total da Memória:");

        lblTotMemMaq2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotMemMaq2.setText("Tamanho do Disco:");

        lblTotMemoMaq01.setText("--------");

        lblTotDiscoMaq01.setText("--------");

        lblTotMemMaq3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotMemMaq3.setText("Numero de CPUs Fisicas:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ID da máquina:");

        lblIdMaq01.setText("-------");

        lblNumCpuFisMaq01.setText("--------");

        btnVerMedidas.setText("Ver medidas");
        btnVerMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMedidasActionPerformed(evt);
            }
        });

        lblFreqProcessMaq01.setText("--------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblHospital01, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel4)
                                .addGap(324, 324, 324))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVerMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCapacidade)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(lblTotMemMaq2)
                            .addComponent(lblTotMemMaq3))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSist_OperMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAlaMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFabricanMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdMaq01)
                            .addComponent(lblNomProcessMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFreqProcessMaq01)
                            .addComponent(lblTotMemoMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotDiscoMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumCpuFisMaq01, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblAlaMaq01)
                        .addGap(20, 20, 20)
                        .addComponent(lblHospital01)
                        .addGap(15, 15, 15)
                        .addComponent(lblSist_OperMaq01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblIdMaq01))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblFabricanMaq01))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomProcessMaq01)
                            .addComponent(jLabel7)
                            .addComponent(btnVerMedidas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCapacidade)
                            .addComponent(lblTotMemoMaq01)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblFreqProcessMaq01))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotMemMaq2)
                    .addComponent(lblTotDiscoMaq01))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotMemMaq3)
                    .addComponent(lblNumCpuFisMaq01))
                .addGap(171, 171, 171))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMedidasActionPerformed
        TelaMedidasMaquina telaMedidas = new TelaMedidasMaquina();
        telaMedidas.setVisible(true);
                
    }//GEN-LAST:event_btnVerMedidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfMaquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerMedidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAlaMaq01;
    private javax.swing.JLabel lblFabricanMaq01;
    private javax.swing.JLabel lblFreqProcessMaq01;
    private javax.swing.JLabel lblHospital01;
    private javax.swing.JLabel lblIdMaq01;
    private javax.swing.JLabel lblNomProcessMaq01;
    private javax.swing.JLabel lblNumCpuFisMaq01;
    private javax.swing.JLabel lblSist_OperMaq01;
    private javax.swing.JLabel lblTotDiscoMaq01;
    private javax.swing.JLabel lblTotMemMaq2;
    private javax.swing.JLabel lblTotMemMaq3;
    private javax.swing.JLabel lblTotMemoMaq01;
    private javax.swing.JLabel txtCapacidade;
    // End of variables declaration//GEN-END:variables
}
